### ISSUE TITLE
updateVersion is creating a lot of extra nodes

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/gltf-pipeline#311] opened 2017-08-29 17:28 UTC
With this model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0/BrainStem/glTF-Binary

The original glTF has 3 meshes, each with 10-25 primitives
The glTF returned from gltf-pipeline has ~50 meshes, each with one primitive.  And each of these new meshes need to be referenced by a node, so it also creates a ton of extra nodes.

As a result, the hierarchy goes from looking like this:
![image](https://user-images.githubusercontent.com/3451886/29834584-53ee26f0-8cbd-11e7-8970-129949219ec6.png)
and after it's processed it looks like this:
![image](https://user-images.githubusercontent.com/3451886/29834610-66ec7afe-8cbd-11e7-8306-a1e2eb39006f.png)

This intuitively doesn't seem as optimal, but I'm not really sure.  @lilleyse is looking into it

**Comment by lasalvavida** [comment] 2017-08-29 17:40
It may be due to `updateVersion` if it is being used. One of the things that changed from glTF 1.0 -> 2.0 is that nodes have a `mesh` property instead of `meshes`. `updateVersion` splits mesh groups on nodes out into new nodes to be compatible with the new spec. 

If this is a newer version of Cesium this could be happening in there and not during the optimization since Cesium uses `updateVersion` to load 1.0 models.

**Comment by lasalvavida** [comment] 2017-08-29 17:43
If that is the reason, it should be possible to change that section of code to combine the primitive arrays of mesh groups on nodes during the update (which is probably more optimal).

**Comment by hpinkos** [comment] 2017-08-29 17:55
Thanks @lasalvavida! Yes, both screenshots are from Cesium 1.36, so the glTF is being updated from 1.0 to 2.0.

That does appear to be the problem.  Everything looks as expected in Cesium 1.35 using glTF 1.0.

**Comment by pjcozzi** [comment] 2017-08-30 12:00
+1 to fixing this soon if anyone has bandwidth.

**Comment by lilleyse** [comment] 2017-08-30 13:23
I'm pretty sure `updateVersion` or anything included in Cesium isn't the problem. It does break apart nodes with multiple meshes correctly but this doesn't add that many nodes. One of the optimization stages is the cause, I don't know which.
<img width="315" alt="graph" src="https://user-images.githubusercontent.com/915398/29874331-6cf2b2c2-8d64-11e7-94d5-78fbdb723049.png">
(Brainstem glb 1.0 dragged onto model inspector)

**Comment by hpinkos** [comment] 2017-08-30 14:05
@lilleyse My guess is there's something going wrong the changes made during the optimization stage and how `updateVersion` processes those changes.  The optimized model has a reasonable hierarchy in Cesium 1.35 using glTF 1.0, but it looks crazy in 1.36 after `updateVersion` converts it to glTF 2.0.

**Comment by lilleyse** [comment] 2018-08-15 02:07
Most likely this was fixed when the optimization stages were removed. The model has 24 nodes after processing now.

**Comment by hpinkos** [comment] 2018-08-15 14:46
@lilleyse I'm seeing the same thing in ion that I did when I opened this issue

**Comment by lilleyse** [comment] 2018-08-15 14:54
I guess the question is should issues remain open that are only a problem on the 1.0 branch? This bug does not happen in master.

**Comment by hpinkos** [comment] 2018-08-15 14:56
Oh did 2.0 get merged into master?  It is probably just the 1.0 branch if that's what we're using

**Comment by lilleyse** [comment] 2018-08-15 14:56
Yeah we merged the 2.0 branch in yesterday.

**Closed** 2018-08-15 14:56 UTC
Labels: priority - high
