### ISSUE TITLE
`removeUnusedVertices` relies on byte strides exclusively

### ISSUE THREAD

**Issue by likangning93** [AnalyticalGraphicsInc/gltf-pipeline#58] opened 2016-06-06 20:00 UTC
I found out that if you run the pipeline on a model that has accessors with `byteStride` set to `0` but `type`  set to `VEC3`, `compressBuffers` in `removeUnusedVertices` strips out too much information and causes an `indexOutOfBounds` error soon after. 

From my reading of the gltf spec ([this part](https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#accessor)) it seems like the pipeline should be able to observe from `"byteOffset": 0` and `"type": "VEC3"` that the data is tightly packed vec3s.

**Comment by pjcozzi** [comment] 2016-06-06 20:17
> From my reading of the gltf spec (this part) it seems like the pipeline should be able to observe from "byteOffset": 0 and "type": "VEC3" that the data is tightly packed vec3s.

Yes, exactly.  Can you open a PR with a fix and a new test?

**Comment by lasalvavida** [comment] 2016-06-06 20:26
Isn't this a duplicate of #57?

**Comment by likangning93** [comment] 2016-06-06 20:30
@lasalvavida I don't think it's exactly the same, but it might be related. I'm getting a crash here instead of a mangled model.

**Closed** 2016-06-09 14:31 UTC
Labels: bug
