### ISSUE TITLE
The removeUnusedVertices stage of the pipeline mangled a model

### ISSUE THREAD

**Issue by lasalvavida** [AnalyticalGraphicsInc/gltf-pipeline#57] opened 2016-06-03 19:47 UTC
The model in question is the chinese dragon model from [here](https://github.com/SaschaWillems/Vulkan/blob/master/models/chinesedragon.obj).

I ran it through obj2gltf to produce this [valid gltf](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/298298/chinesedragon.zip).

![dragon-normal](https://cloud.githubusercontent.com/assets/2489570/15790933/68a27b16-29a2-11e6-950f-fa0fde2ec1b8.PNG)

Remove unusedVertices outputs [this](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/files/298302/chinesedragon-mangled.zip).

![chinese-dragon-mangled](https://cloud.githubusercontent.com/assets/2489570/15790931/66ce58f0-29a2-11e6-9941-288759576122.png)

**Comment by lasalvavida** [comment] 2016-06-03 20:05
In this model, the positions, normals and uv are all stored in the same bufferView, but interleaved. I suspect this is caused by the optimizer identifying that uv is unused but not identifying the interleaving.

I think a good solution would be to add a stage to un-interleave data as this also breaks some of the assumptions in quantization.

**Comment by pjcozzi** [comment] 2016-06-03 20:07
Stages to un-interleave and interleave could be fine.

Is it possible/reasonable for the quantization to work with interleaved data by working with the offset and stride?

**Comment by lasalvavida** [comment] 2016-06-03 20:15
It is possible; currently it slices up and repackages the buffer, so it won't work (or be very efficient) with that approach. It is probably better to do all of the repacking once and to copy into a single buffer, so this may be reasonable doing things that way.

**Comment by leerichard42** [comment] 2016-06-03 20:49
I had the same problem with other models, so I will be going back and taking another look at the removeUnusedVertices stage soon.

**Comment by leerichard42** [comment] 2016-06-03 20:58
If the un-interleaving stage is added, should removeUnusedVertices be commented out for now and tried again with that extra stage?

**Comment by pjcozzi** [comment] 2016-06-03 21:05
> If the un-interleaving stage is added, should removeUnusedVertices be commented out for now and tried again with that extra stage?

This is fine as long as the `removeUnusedVertices` always depends on the `un-interleaving` stage.

@lilleyse @likangning93 @JoshuaStorm for configuring pipelines, I think we are going to need each stage to know its dependencies on previous stages (think like C++ `include`), and then resolve this so we don't do duplicate work.  Same comment for post-process stages like merging buffers.

**Comment by pjcozzi** [comment] 2016-06-10 11:55
@lilleyse did you reopen this because the issue is not fixed or because we want to add the stage dependencies mentioned above?

**Comment by lasalvavida** [comment] 2016-06-10 12:18
Something must have changed between the last time I tested this and now, I'll look into it. All of the indices are being written as 0's.

**Comment by lilleyse** [comment] 2016-06-10 14:38
> @lilleyse did you reopen this because the issue is not fixed or because we want to add the stage dependencies mentioned above?

I accidentally closed it yesterday, and reopened.

**Closed** 2016-06-10 15:09 UTC
Labels: bug

**Comment by lilleyse** [comment] 2016-06-10 15:13
Now actually closed, fixed in #72.
